/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/modelos/angell.glb 
Author: SinisterClock (https://sketchfab.com/multi_2024)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/small-screen-drone-6117-fs-angel-bfe3cd9aa03f49c4b7dfd8158f19d1a3
Title: Small Screen Drone : 6117 (FS_Angel)
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'
import { useEffect } from 'react'

export function Angell(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/modelos/angell.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    if (actions) {
      Object.values(actions).forEach((action) => {
        action.reset().fadeIn(0.5).play()
      })
    }
  }, [actions])
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Armature_27" position={[0, 1.443, 0.13]} rotation={[Math.PI / 2, 0, 0]} scale={0.7}>
                <group name="GLTF_created_0">
                  <primitive object={nodes.GLTF_created_0_rootJoint} />
                  <group name="Object_181359_13" />
                  <group name="Object_22003_14" />
                  <group name="Object_22005_15" />
                  <group name="Object_22008_16" />
                  <group name="Object_22010_17" />
                  <group name="Object_306001_18" />
                  <group name="Object_306002_19" />
                  <group name="Object_306003_20" />
                  <group name="Object_306004_21" />
                  <group name="Object_306005_22" />
                  <group name="Object_306006_23" />
                  <group name="Object_306007_24" />
                  <group name="Object_306008_25" />
                  <group name="Object_306009_26" />
                  <skinnedMesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials['Upper_body_Diff.001']} skeleton={nodes.Object_7.skeleton} />
                  <skinnedMesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials['combine_monitor002.001']} skeleton={nodes.Object_8.skeleton} />
                  <skinnedMesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials.combine_innerwall001} skeleton={nodes.Object_9.skeleton} />
                  <skinnedMesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials['TV.001']} skeleton={nodes.Object_10.skeleton} />
                  <skinnedMesh name="Object_11" geometry={nodes.Object_11.geometry} material={materials['Screen.001']} skeleton={nodes.Object_11.skeleton} />
                  <skinnedMesh name="Object_12" geometry={nodes.Object_12.geometry} material={materials['Material.001']} skeleton={nodes.Object_12.skeleton} />
                  <skinnedMesh name="Object_13" geometry={nodes.Object_13.geometry} material={materials.Screen} skeleton={nodes.Object_13.skeleton} />
                  <skinnedMesh name="Object_15" geometry={nodes.Object_15.geometry} material={materials.Material_19} skeleton={nodes.Object_15.skeleton} />
                  <skinnedMesh name="Object_16" geometry={nodes.Object_16.geometry} material={materials.Material_19} skeleton={nodes.Object_16.skeleton} />
                  <skinnedMesh name="Object_17" geometry={nodes.Object_17.geometry} material={materials.Material_16} skeleton={nodes.Object_17.skeleton} />
                  <skinnedMesh name="Object_19" geometry={nodes.Object_19.geometry} material={materials.Material_18} skeleton={nodes.Object_19.skeleton} />
                  <skinnedMesh name="Object_20" geometry={nodes.Object_20.geometry} material={materials['arm_diffuse.002']} skeleton={nodes.Object_20.skeleton} />
                  <skinnedMesh name="Object_21" geometry={nodes.Object_21.geometry} material={materials.Material_17} skeleton={nodes.Object_21.skeleton} />
                  <skinnedMesh name="Object_23" geometry={nodes.Object_23.geometry} material={materials.Material_19} skeleton={nodes.Object_23.skeleton} />
                  <skinnedMesh name="Object_24" geometry={nodes.Object_24.geometry} material={materials.Material_19} skeleton={nodes.Object_24.skeleton} />
                  <skinnedMesh name="Object_25" geometry={nodes.Object_25.geometry} material={materials.Material_16} skeleton={nodes.Object_25.skeleton} />
                  <skinnedMesh name="Object_27" geometry={nodes.Object_27.geometry} material={materials.Material} skeleton={nodes.Object_27.skeleton} />
                  <skinnedMesh name="Object_28" geometry={nodes.Object_28.geometry} material={materials['arm_diffuse.002']} skeleton={nodes.Object_28.skeleton} />
                  <skinnedMesh name="Object_29" geometry={nodes.Object_29.geometry} material={materials.Material_17} skeleton={nodes.Object_29.skeleton} />
                  <skinnedMesh name="Object_31" geometry={nodes.Object_31.geometry} material={materials['d_platform_shield.001']} skeleton={nodes.Object_31.skeleton} />
                  <skinnedMesh name="Object_33" geometry={nodes.Object_33.geometry} material={materials.d_platform_shield} skeleton={nodes.Object_33.skeleton} />
                  <skinnedMesh name="Object_35" geometry={nodes.Object_35.geometry} material={materials['interloper_rings.003']} skeleton={nodes.Object_35.skeleton} />
                  <skinnedMesh name="Object_37" geometry={nodes.Object_37.geometry} material={materials['d_platform_shield.002']} skeleton={nodes.Object_37.skeleton} />
                  <skinnedMesh name="Object_39" geometry={nodes.Object_39.geometry} material={materials['interloper_rings.003']} skeleton={nodes.Object_39.skeleton} />
                  <skinnedMesh name="Object_41" geometry={nodes.Object_41.geometry} material={materials.int_copper00b_prop} skeleton={nodes.Object_41.skeleton} />
                  <skinnedMesh name="Object_43" geometry={nodes.Object_43.geometry} material={materials.xenxen_metal_trim_01a_prop} skeleton={nodes.Object_43.skeleton} />
                  <skinnedMesh name="Object_45" geometry={nodes.Object_45.geometry} material={materials.damo_reactor_coolingpod} skeleton={nodes.Object_45.skeleton} />
                  <skinnedMesh name="Object_47" geometry={nodes.Object_47.geometry} material={materials.damo_portal_coolingpod} skeleton={nodes.Object_47.skeleton} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/angell.glb')
