/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/modelos/dna_hologram.glb 
Author: oxterium (https://sketchfab.com/oxterium)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/dna-hologram-c4a30768ac7044f182b4c4a36a7608ca
Title: DNA hologram
*/

import React, { useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function ADN(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/modelos/dna_hologram.glb')
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    if(actions) {
      Object.values(actions).forEach((action) => {
        action.reset().play()
        action.timeScale = 0.3
      })
    }
  }, [actions])
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="a467a8f058f4444993a7605bba02b5bafbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Sphere3514" rotation={[1.551, 0, 0]} scale={100}>
                  <mesh name="Sphere3514_particle_2_0" geometry={nodes.Sphere3514_particle_2_0.geometry} material={materials.particle_2} />
                  <mesh name="Sphere3514_Particle_1_0" geometry={nodes.Sphere3514_Particle_1_0.geometry} material={materials.Particle_1} />
                  <mesh name="Sphere3514_Particle_1_0_1" geometry={nodes.Sphere3514_Particle_1_0_1.geometry} material={materials.Particle_1} />
                  <mesh name="Sphere3514_Particle_1_0_2" geometry={nodes.Sphere3514_Particle_1_0_2.geometry} material={materials.Particle_1} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/dna_hologram.glb')
