/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/modelos/holograma_planeta.glb 
Author: DennisGray (https://sketchfab.com/DennisGray)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/hologram-planetary-map-4e60b10f849241319e6e243482dd1b2b
Title: Hologram Planetary Map
*/

import React, { useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export function HologramaPlaneta(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/modelos/holograma_planeta.glb')
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    if (actions) {
      Object.values(actions).forEach((action) => {
        action.reset().play()
        action.timeScale = 0.2
      })
    }
  }, [actions])

  // useFrame(() => {
  //   if (group.current) {
  //     group.current.rotation.x += 0.002
  //   }
  // })

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="28dea611a67c47a787a5476869fb9e01fbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="MASH1_ReproMesh" position={[-64.354, 21.675, -208.798]}>
                  <mesh name="MASH1_ReproMesh_Holo_0" geometry={nodes.MASH1_ReproMesh_Holo_0.geometry} material={materials.Holo} />
                  <mesh name="MASH1_ReproMesh_Holo_0_1" geometry={nodes.MASH1_ReproMesh_Holo_0_1.geometry} material={materials.Holo} />
                  <mesh name="MASH1_ReproMesh_Holo_0_2" geometry={nodes.MASH1_ReproMesh_Holo_0_2.geometry} material={materials.Holo} />
                </group>
                <group name="MASH4_ReproMesh" position={[-64.354, 21.675, -208.798]}>
                  <mesh name="MASH4_ReproMesh_Ring_0" geometry={nodes.MASH4_ReproMesh_Ring_0.geometry} material={materials.Ring} />
                </group>
                <group name="MASH3_Trails_Mesh" position={[-64.354, 21.675, -208.798]}>
                  <mesh name="MASH3_Trails_Mesh_Latice_0" geometry={nodes.MASH3_Trails_Mesh_Latice_0.geometry} material={materials.Latice} />
                </group>
                <group name="HologramTableBasepPlane3" position={[-65.122, 62.437, -207.772]} scale={0.908}>
                  <mesh name="HologramTableBasepPlane3_lambert38_0" geometry={nodes.HologramTableBasepPlane3_lambert38_0.geometry} material={materials.lambert38} />
                </group>
                <group name="pCube32" position={[211.845, -2.439, 8.282]} rotation={[0, 0.816, 0]}>
                  <mesh name="pCube32_lambert41_0" geometry={nodes.pCube32_lambert41_0.geometry} material={materials.lambert41} />
                </group>
                <group name="pCube33" position={[284.987, -2.439, -245.272]} rotation={[-Math.PI, 1.554, -Math.PI]}>
                  <mesh name="pCube33_lambert41_0" geometry={nodes.pCube33_lambert41_0.geometry} material={materials.lambert41} />
                </group>
                <group name="pCube35" position={[152.728, -2.439, -484.743]} rotation={[-Math.PI, 0.754, -Math.PI]}>
                  <mesh name="pCube35_lambert41_0" geometry={nodes.pCube35_lambert41_0.geometry} material={materials.lambert41} />
                </group>
                <group name="pCube36" position={[-107.791, -2.439, -557.331]} rotation={[-Math.PI, -0.036, -Math.PI]}>
                  <mesh name="pCube36_lambert41_0" geometry={nodes.pCube36_lambert41_0.geometry} material={materials.lambert41} />
                </group>
                <group name="pCube37" position={[-339.048, -2.439, -427.973]} rotation={[-Math.PI, -0.809, -Math.PI]}>
                  <mesh name="pCube37_lambert41_0" geometry={nodes.pCube37_lambert41_0.geometry} material={materials.lambert41} />
                </group>
                <group name="pCube38" position={[-27.484, -2.439, 140.882]} rotation={[0, 0.018, 0]}>
                  <mesh name="pCube38_lambert41_0" geometry={nodes.pCube38_lambert41_0.geometry} material={materials.lambert41} />
                </group>
                <group name="pCube39" position={[-413.701, -2.439, -168.327]} rotation={[0, -1.544, 0]}>
                  <mesh name="pCube39_lambert41_0" geometry={nodes.pCube39_lambert41_0.geometry} material={materials.lambert41} />
                </group>
                <group name="pCube40" position={[-280.784, -2.439, 68.206]} rotation={[0, -0.751, 0]}>
                  <mesh name="pCube40_lambert41_0" geometry={nodes.pCube40_lambert41_0.geometry} material={materials.lambert41} />
                </group>
                <group name="pPlane3" position={[-63.978, -19.705, -207.772]} rotation={[0, 0, -Math.PI]} scale={0.908}>
                  <mesh name="pPlane3_lambert38_0" geometry={nodes.pPlane3_lambert38_0.geometry} material={materials.lambert38} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/holograma_planeta.glb')
